version: '3.3'
services:
  app:
    image: spudin/wot_tactics
    ports:
    - "3000:3000"
  wot_redis:
    container_name: wot_redis
    image: redis
    ports:
      - "6379:6379"
  wot_mongo:
    container_name: wot_mongo
    image: mongo
    ports:
      - "27017:27017"